services:
  - type: web
    name: berkeley-brew-api
    env: node
    buildCommand: cd packages/api && npm install && npm run build
    startCommand: cd packages/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://berkeley-brew.netlify.app
