name: Popular Times Scheduler

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight (UTC)
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: popular-times
  cancel-in-progress: true

jobs:
  run-script:
    name: Run fetch_popular_times.py
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "PWD:" && pwd
          echo "Listing files:" && ls -la
          echo "requirements.txt (packages/api):" && sed -n '1,120p' requirements.txt || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: packages/api/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install "git+https://github.com/m-wrzr/populartimes@master"

      - name: Run popular times script
        env:
          # Google key for populartimes/geocoding
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

          # Database connection - use available secrets
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          
          # Supabase connection (already available)
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          python scripts/fetch_popular_times.py
